main: me.lorenzo.CustomLore
name: CustomLore
version: 1.0

commands:
  setname:
    usage: </command>
    description: Set an item's name!
  setlore:
    usage: </command>
    description: Set an item's lore!